### ISSUE TITLE
Spinning Circle on Editor

### ISSUE THREAD

**Issue by tnayrb03** [AllanOricil/vscode-salesforce-query-editor#14]
When i spin up the Editor it just leaves a blank screen with a spinner.

**Comment by AllanOricil** [comment]
> When i spin up the Editor it just leaves a blank screen with a spinner.

Could you share your vscode, sfdx and node versions. Also which OS are you using?

**Comment by ciskrabaczAscent** [comment]
I too am experiencing this problem.  I am on vscode 1.55.2, v.1.7.2 of the query editor.  Running on Windows 10.  sfdx 52.13.0

**Comment by tnayrb03** [comment]
Sorry for the delay i am on vs code Version: 1.53.2, v1.7.2 of the editor. Running on IOS Big Sur. node v14.2.0

**Comment by AllanOricil** [comment]
@tnayrb03 and @ciskrabaczAscent could you guys update VSCode to 1.6 and the extension to 1.8.0

**Comment by ciskrabaczAscent** [comment]
Thank you.

That resolved the issue.

Craig Skrabacz
Application Development Manager
Ascent Global Logistics
Office: 331.233.7757
