### ISSUE TITLE
How do you open SOQL files with this?

### ISSUE THREAD

**Issue by RugerSR762** [AllanOricil/vscode-salesforce-query-editor#16]
Since the SOQL Builder from the Salesforce Extension Pack is trash and no longer toggles between the builder and the code view, I am trying this tool.  However, I cannot open SOQL files with it.  Per the instructions, you should be able to right-click on a file and open using this editor, however there are no options to do so:

<img width="235" alt="vscode_soql1" src="https://user-images.githubusercontent.com/48356164/149403387-92ce87f3-3e7c-428a-b959-7be3c91eebf0.png">

**Comment by AllanOricil** [comment]
@RugerSR762 I did no implement support for .soql files because I never really saw them useful. With my extension you can create/type your query directly on the UI. But if you want to keep using .soql files, I can support them. I would just read the content of the .soql and execute the query for you. Would that be enough?

**Comment by RugerSR762** [comment]
> 

Ahhh OK... Sorry for misunderstanding that.  Being able to create/type the queries within the UI is cool for me.  I guess I just create a new project then using your tool and I should then be able to simply copy/paste the existing queries into the editor, correct?

**Comment by RugerSR762** [comment]
When I open the SF Query Editor, it does not go beyond this:

<img width="219" alt="vscode_soql2" src="https://user-images.githubusercontent.com/48356164/149408424-8eb840ba-adb8-4bbc-a6a0-64316fa609d4.png">

**Comment by AllanOricil** [comment]
@RugerSR762 could you share your OS, the extension version, the sfdx version, the vscode version. Also, you have to make sure you have a default org set in sfdx before opening the extension.

**Comment by RugerSR762** [comment]
> @RugerSR762 could you share your OS, the extension version, the sfdx version, the vscode version. Also, you have to make sure you have a default org set in sfdx before opening the extension.

Sure:

**OS and version**:
Edition Windows 10 Pro
Version 20H2
Installed on ‎9/‎30/‎2021
OS build 19042.1466
Experience Windows Feature Experience Pack 120.2212.3920.0

**Salesforce Extension Version in VS Code**: v53.13

**SFDX CLI Version**: v53.13

**VS Code Version**: 1.63.2

**SF Query Editor**: v1.8

**Comment by RugerSR762** [comment]
@AllanOricil I think I got it now.. I went ahead and created a new project, authorized the org and now I can connect to your app.  I'll let you know if I have any further issues!
Cheers!

**Comment by RugerSR762** [comment]
PS - hope you got your cup of coffee :-)

**Comment by AllanOricil** [comment]
@RugerSR762 no worries. Good you made it work. Im working again on the extension and I will make sure that people are able to setup it properly and easily.
