### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by matcaampos** [AllanOricil/vscode-salesforce-query-editor#7]
Boa tarde Alan, uma dúvida, sou um desenvolvedor Salesforce e trabalho bastante com o Dx, inclusive em projetos grandes, e um problema que temos é em relação ao tempo que perdemos quando criamos uma nova scratch org, por que ela vem limpa, sem dados, vi seu vídeo de apresentação do Query Editor, e estou utilizando ele, inclusive, parabéns, ficou ótimo..... a dúvida é o seguinte tem como exportar uma massa de dados grande de da minha org QA para a minha scratch org pelo Query Editor?

---
Good afternoon Alan, a question, I'm a Salesforce developer and I work a lot with Dx, including on large projects, and a problem we have is related to the time we waste when we create a new scratch org, because it comes clean, with no data , I saw your Query Editor presentation video, and I'm using it, congratulations, it was great..... the question is, how can I export a large mass of data from my QA org to my scratch org by Query Editor?

**Comment by AllanOricil** [comment]
O Query Editor é realmente apenas para executar queries. Eu pensei em adicionar mais coisas relacionadas a exportação de dados mas o escopo ficaria grande e eu não daria conta de manter a ferramenta. Aí eu perguntei pro pessoal se gostariam de um Data Loader no Vscode. Gostaram da ideia, aí eu estou desenvolvendo uma extensão que empacota o Data Loader CLI, mas com a interface sendo exibida dentro do vscode. Assim a gente não vai mais perder tempo instalando outras ferramentas. Mas vai demorar um pouco pra eu deixar publico. Ainda tenho investir tempo para corrigir os bugs que apareceram no query editor por conta dos updates do vscode.
